name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Making gradle executable
      run:  chmod +x ./gradlew
    - name: Making gradle executable
      run:  git update-index --chmod=+x ./gradlew
    - name: Build with making Gradle executable
      run: ./gradlew build
